apiVersion: v1
kind: Namespace
metadata:
  name: VAR_NAMESPACE_REPLACER
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: VAR_SERVICE_ACCOUNT_NAME_REPLACER
  namespace: VAR_NAMESPACE_REPLACER
secrets:
  - name: VAR_SERVICE_ACCOUNT_NAME_REPLACER-token
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: VAR_SERVICE_ACCOUNT_NAME_REPLACER-token
  namespace: VAR_NAMESPACE_REPLACER
  annotations:
    kubernetes.io/service-account.name: VAR_SERVICE_ACCOUNT_NAME_REPLACER
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: VAR_SERVICE_ACCOUNT_NAME_REPLACER-clusterrole
rules:
  - apiGroups:
      - ''
      - apps
      - networking.k8s.io
      - batch
    resources:
      - namespaces
      - deployments
      - replicasets
      - ingresses
      - services
      - secrets
      - cronjobs
      - jobs
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: VAR_SERVICE_ACCOUNT_NAME_REPLACER-binding
subjects:
- kind: ServiceAccount
  name: VAR_SERVICE_ACCOUNT_NAME_REPLACER
  namespace: VAR_NAMESPACE_REPLACER
roleRef:
  kind: ClusterRole
  name: VAR_SERVICE_ACCOUNT_NAME_REPLACER-clusterrole
  apiGroup: rbac.authorization.k8s.io